language: node_js
node_js:
  - "node"
install:
  # Install meteor
  - curl https://install.meteor.com/ | sh
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
  - export PATH=$HOME/.meteor:$PATH

script:
- meteor test --once

cache:
  directories:
    - node_modules
